
STEPPS2 ?= $(HOME)/Documents/paleon/stepps2

PREDICTION ?= $(HOME)/Documents/projects/stepps-prediction

#include $(STEPPS2)/Makefile210.inc
#include $(STEPPS2)/Makefile240.inc
include $(PREDICTION)/Makefile262.inc

all: veg_od_mpp_262.exe


